# Generated by Django 3.2.12 on 2024-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=250)),
                ('link_blog', models.CharField(default='#', max_length=250)),
                ('blog', models.CharField(default='#', max_length=250)),
                ('image', models.ImageField(upload_to='images')),
                ('tags', models.ManyToManyField(to='qualifications.Tag')),
            ],
        ),
    ]
