# Generated by Django 4.1.1 on 2023-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_link_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="blog",
            field=models.CharField(default="#", max_length=250),
        ),
        migrations.AlterField(
            model_name="project",
            name="link_blog",
            field=models.CharField(default="#", max_length=250),
        ),
    ]
