version: '3.7'
services:
    db:
        container_name: pfolio_db
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=heidless
            - POSTGRES_PASSWORD=havana11
            - POSTGRES_DB=hpfolio
        ports: 
            - 5432:5432
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=heidless
            - POSTGRES_PASSWORD=havana11
        depends_on:
            - db
    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment: 
            - PGADMIN_DEFAULT_EMAIL=rob.lockhart@yahoo.co.uk
            - PGADMIN_DEFAULT_PASSWORD=arjuna11
        ports: 
            - '5050:80'